#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
galeries_search:
    path: '/search'
    controller: 'App\Controller\GaleriesController::search'
    methods: ['GET']

